spring:
  application:
    name: ms-integracion-message-producer
  
  config:
    import: optional:configserver:http://localhost:8888

#  cloud:
#    loadbalancer:
#      health-check:
#       interval: 15s