server:
   port: 8090
      
# Kafka #
kafka:
#  bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
  bootstrap-servers: localhost:9092
  topic: 
#   topic-pedido-resumen: topic-pedido
    topic-pedido-autorizacion-pendiente-automatico: topic-pedido-autorizacion-pendiente-automatico
    topic-pedido-autorizacion-evaluado: topic-pedido-autorizacion-evaluado
  group:
     group-pedido-autorizacion-pendiente-automatico: group-pedido-autorizacion-pendiente-automatico-id 
     group-pedido-autorizacion-evaluado: group-pedido-autorizacion-evaluado-id  
  retry:
     retryIntervalMilliseconds: 10000
     maxRetryDurationMilliseconds: 60000
     retryBackoffMultiplier: 2
     maxRetryAttempts: 3
     autoCreateRetryTopics: true
# Server Admin Client 
spring:
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port:8090}

# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always

# Feign client         
feign:
  client:
    config:
      httpBinClient:
        read-timeout: 2000
        connect-timeout: 1000
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
# Microservices Client - Negocio
ms-negocio-gestion-pedidos.url: http://localhost:8084/v1/pedidos
ms-negocio-gestion-productos.url: http://localhost:8082/v1/productos