server:
  port: 8887

spring:
  # Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port:8887}

  # Mapeo de Microservicios
  cloud:
    gateway:
      discovery:
        locator:
          # Deshabilitar routes autogeneradas
          #           enabled: false
          enabled: true
        lowerCaseServiceId: true
      route-refresh-listener:
        enabled: false
      # Personalizado - Routers
      routes:
        - id: id-ms-clientes
          uri: lb://MS-NEGOCIO-GESTION-CLIENTES
          predicates:
            - Path=/ms-clientes/**
          filters:
            - RewritePath=/ms-clientes/(?<path>.*), /$\{path}
        - id: id-ms-productos
          uri: lb://MS-NEGOCIO-GESTION-PRODUCTOS-ORACLE
          predicates:
            - Path=/ms-productos/**
          filters:
            - RewritePath=/ms-productos/(?<path>.*), /$\{path}
        - id: albums
          uri: https://jsonplaceholder.typicode.com/albums
          predicates:
            - Path=/albums

# Server Registry Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka

# Activacion de endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      # Deshabilitar routes autogeneradas
      #         enabled: false
      enabled: true
    health:
      show-details: always
