server:
   port: 8086
      
# Kafka #
kafka:
#  bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
  bootstrap-servers: localhost:9092
  topic: 
     topic-pedido-resumen: topic-pedido-resumen
# Server Admin Client
spring:
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port:8086}

# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always