server:
  port: 8085
# MySql #
# spring.jpa.hibernate.ddl-auto=update
spring:
  # MySQL
  #  jpa:
  #    show-sql: true
  #    hibernate:
  #      ddl-auto: create
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DB_MS_CLIENTES:db_curs-000189_clientes?createDatabaseIfNotExist=true&useSSL=true}
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #spring.jpa.show-sql: true

  # Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port}

# Server Registry Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka

# Endpoints exposition
management:
  endpoints:
    web:
      exposure:
        include: "*"
      health:
        show-details: always
